version: '3'

services: 

    go:
        image: 'golang:1.13'

        ports: 
            - '8800:8800'

        tty: true

        working_dir: /go/src/gin/

        volumes: 
            - './:/go/src/gin/'

        command: go run main.go
